### ISSUE TITLE
Error, not sure what for

### ISSUE THREAD

**Issue by kingreboot** [sfmict/MountsJournal#10]
2x MountsJournal\config\About.lua:104: attempt to index global 'Settings' (a nil value)
[string "@MountsJournal\config\About.lua"]:104: in main chunk

Locals:
addon = "MountsJournal"
L = <table> {
 MOUNT_FACTION_3 = "Both"
 About = "About"
 Help with translation of %s. Thanks. = "Help with translation of %s. Thanks."
 Zones with flags = "Zones with flags"
 types = "Types"
 ZoneSettingsTooltipDescription = "Creating a list of mounts for the zone.

Configuring zone flags.

Setting up relations to use one list of mounts in different zones."
 Add tag = "Add Tag"
 SecondMountTooltipTitle = "If the modifier is hold or “%s 2” is used:"
 Run = "Run"
 Swim = "Swim"
 Shown: = "Shown:"
 Reverse Sort = "Reverse Sort"
 WaterWalkFlagDescription = "Used to configure some classes."
 Select all mounts by type in selected zone = "Select all mounts by type in the selected zone"
 factions = "Factions"
 NoPetInRaid = "Do not summon battle pet in raid group"
 With multiple models = "With only multiple models"
 Set current filters as default = "Set current filters as default"
 PET_4 = "Without Pet"
 CHARACTER_CLASS_DESCRIPTION = "(character settings override class settings)"
 UseUnderlightAnglerDescription = "Use Underlight Angler instead of underwater mounts."
 Fly = "Fly"
 UseMagicBroomTitle = "Use Magic Broom"
 Random available mount = "Random available mount"
 Are you sure you want to delete profile %s? = "Are you sure you want to delete profile "%s"?"
 Restore default filters = "Restore default filters"
 ConfigPanelTitle = "Global settings"
 Default = "Default"
 MOUNT_TYPE_1 = "Flying"
 SecondMountTooltipDescription = "If you are in water then will be summoned non-waterfowl mount.

If you are on land and you can fly then will be summoned ground mount."
 Favorites First = "Favorites First"
 PET_3 = "With Pet"
 CopyMountTarget = "Try to copy target's mount"
 UseHerbMounts = "Use Mount for Herbalism"
 sources = "Sources"
 UseRepairMountsDescription = "If the durability of at least one item is less than the specified percentage, the selected mount will be summoned."
 Water Walking = "Water Walking"
 UseHerbMountsOnZones = "Only in Herb Gathering Zones"
 CreateMacroTooltip = "The created macro is used to summon the selected mounts."
 = (equal to) = "= (equal to)"
 A profile with the same name exists. = "A profile with the same name exists."
 ListMountsFromZone = "Use list of mounts from zone"
 Initial x-axis accseleration = "Initial X-axis Accseleration"
 CLASS_USEWHENCHARACTERFALLS = "Use the %s when the character falls"
 Fly backwards = "Fly backwards"
 HerbGatheringFlagDescription = "Used to configure use of Mount to Herbalism."
 Profile settings = "Profile settings"
 Enable Acceleration around the X-axis = "Enable Acceleration around the X-axis"
 DRUID_USEDRUIDFORMSPECIALIZATION = "Return a specialization form"
 > (more than) = "> (more than)"
 Normal mount summon = "Normal mount summon."
 Hidden by player = "Hidden by player"
 CLASS_USEWATERWALKINGSPELL = "Use the %s when summoning ground mount"
 CLASS_USEONLYWATERWALKLOCATION = "Use only in water walk zones"
 ZoneSettingsTooltip = "Zone settings features"
 Y-axis accseleration = "Y-axis Accseleration"
 Are you sure you want to delete animation %s? = "Are you sure you want to delete animation "%s"?"
 By Specialization = "By Specialization"
 In flyable zones = "In flyable zones"
 < (less than) = "< (less than)"
 Auto add new mounts to selected = "Auto add new mounts to selected"
 Herb Gathering = "Herb Gathering"
 Create = "Create"
 Profiles = "Profiles"
 Enable Flags = "Enable Flags"
 Zones settings from default profile = "Zones settings from default profile"
 Walk = "Walk"
 Pet binding from default profile = "Pet binding from default profile"
 Current Location = "Current Location"
 UseMagicBroomDescription = "When "Hallow's End" event is active, if you have a "Magic Broom", it is used."
 Are you sure you want %s? = "Are you sure you want "%s"?"
 Click opens in = "Click opens in"
 Modifier = "Modifier"
 Collected: = "Collected"
 With all tags = "With All Tags"
 Ground Mounts Only = "Ground Mounts Only"
 Map / Model = "Map / Model"
 author = "Author"
 PET_1 = "With Random Favorite Pet"
 Class settings = "Class settings"
 Localization Transl

**Comment by kingreboot** [comment]
on version v10.0.0-beta1. I now just noticed this is the DF version that wowup grabbed for retail

**Comment by sfmict** [comment]
so, closed :)
