### ISSUE TITLE
Priority Request: Target Mount > Magic Broom

### ISSUE THREAD

**Issue by YWI** [sfmict/MountsJournal#11]
Feature Request, 

Please introduce having to "Try to copy target's mount" overwrite "Use Magic Broom" I use the Halloween broom for mobile though wish to copy target mounts.. Maybe if a target is set have it ignore the broom prio?

**Comment by sfmict** [comment]
Hello, the Magic Broom is used in priority because it is used instantly, but maybe you're right, I'll think.

**Comment by YWI** [comment]
Well yes of course though if there is a target, it shouldn't matter if a person if trying to be efficient or wants to insta a mount just make sure you don't have a target mimicking mount is one of the primary reasons why I use this addon.

**Comment by sfmict** [comment]
Fixed, check next year :)
