### ISSUE TITLE
/click MountsJournal_Mount no longer working

### ISSUE THREAD

**Issue by williamrdickson** [sfmict/MountsJournal#12]
A macro using:

    /click [btn:1] MountsJournal_Mount

...is no longer performing any action (it was working in the previous version I had installed, which I believe was alpha 3).

    /mount

...works fine, but doesn't accept a modifier, making my [btn:2] command for my repair mount fail.

#### Environment
* Addon version: 10.0.3
* WoW version: 10.0.3

#### Steps to reproduce
As above.

#### Expected Behaviour
Selected mount summoned

#### Actual Behaviour
Nothing happens

#### Debug Output
No errors.

**Comment by YWI** [comment]
Also can confirm, since new class release, macro is dead.

**Comment by Swarfimus** [comment]
Any ideas how to get this working again?

**Comment by YWI** [comment]
I'm sure the author is aware, have some patience...

**Comment by Swarfimus** [comment]
> I'm sure the author is aware, have some patience...

Can you crawl back under your bridge, you insufferable jerk?

**Comment by YWI** [comment]
What why are you crying just letting you know the author is notified he'll fix it when he can... 
fragile butterfly

**Comment by Swarfimus** [comment]
> What why are you crying just letting you know the author is notified he'll fix it when he can...
> fragile butterfly

Like I said, back under the bridge with you.  Don't come out again.

**Comment by YWI** [comment]
haha

**Comment by sfmict** [comment]
Hello, fixed, just recreate the macro in the settings.

**Comment by Swarfimus** [comment]
> Hello, fixed, just recreate the macro in the settings.

Thank you.
