### ISSUE TITLE
Summon % enhance

### ISSUE THREAD

**Issue by YWI** [sfmict/MountsJournal#13]
Hello would it be possible to allow us to have mounts summon at 0.001% for example?

currently, its tied to a minimum of 0.1%![image](https://user-images.githubusercontent.com/26565697/204130944-dfe3d4fe-36a6-4faa-86c4-0b5a571471b0.png)

**Comment by sfmict** [comment]
Hello,  now the minimum percent is 1. To calculate the chance of a summon with a probability 0.1, you need to check 1000 records and not 100, and so on. If you take too large values, a lag is possible, so it's better not to do this.

**Comment by sfmict** [comment]
In fact, now the minimum check is equal to the number of mounts, if I change the code. But I'm not sure if this is necessary, since 1% is already a very rare occurrence, since it does not correspond to 100, but to the sum of all chances.

**Comment by sfmict** [comment]
If you want decrease the chance of a mount being summoned, just increase the chance for others.
