### ISSUE TITLE
Dragonriding Support

### ISSUE THREAD

**Issue by panseit** [sfmict/MountsJournal#14]
#### Environment
* Addon version: 10.0.4
* WoW version: 10.0.2

It would be nice if there was an option to summon the dragonriding mount on DF zones and not the other ones.

**Comment by sfmict** [comment]
Hello, you can set any mounts for any zones so i don't quite understand what do you want.

**Comment by panseit** [comment]
You are correct.... I forgot about that feature.... Sorry for opening a ticket :/
