### ISSUE TITLE
Feature request: port to WoTLK Classic

### ISSUE THREAD

**Issue by Barov2** [sfmict/MountsJournal#17]
#### Environment
* WoW version: WotLK Classic 3.4.3

#### Now that WoTLK Classic (version 3.4.3) has a Collections User Interface like Retail, could you port MountsJournal to WotLK Classic? (I know about the existence of MountsJournal_Classic, but MountsJournal would fit better with Blizzard's new UI.)
 Thank you so much.

**Comment by sfmict** [comment]
Hello, I made this a year ago :) https://github.com/sfmict/MountsJournal_Classic

**Comment by Barov2** [comment]
Oh, sorry, I don't play Retail, but I was still under the impression that MountsJournal was better integrated into Blizzard's UI than MountsJournal_Classic.
