### ISSUE TITLE
Random bug

### ISSUE THREAD

**Issue by Acivien** [sfmict/MountsJournal#18]
#### Environment
* Addon version: 10.1.12
* WoW version: 10.1.7.51754

To be honest, I don't really know. I think it's when I mount up, but not sure. It seems random to me.

It's random.

It's random.

12x [ADDON_ACTION_BLOCKED] AddOn 'MountsJournal' tried to call the protected function 'MultiBarRightButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:194: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:346: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:799: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:196: in function <FrameXML/ActionButton.lua:193>

**Comment by sfmict** [comment]
Hello, more likely this is a taint of some addon.

Could you please run this command in-game directly after loading your character:
/console taintLog 1
(default is 0)
And then play until you get these errors again? once you do, please log out (this is crucial, the client uses a buffer for writing to the log and it can take up to 10 minutes for errors to appear) and upload the contents of World of Warcraft\Logs\taint.log to pastebin and paste the link here.

**Comment by Acivien** [comment]
Hi, I've been trying to replicate it, but it seems it was just a random
error. If it happens again I'll be sure to send you a taint log.
