### ISSUE TITLE
Blocked UI action - Changing Guild Rank

### ISSUE THREAD

**Issue by CTOUT** [sfmict/MountsJournal#2]
#### Environment
* Addon version: 8.3.1
* WoW version: 8.3

#### Steps to reproduce
Open Guild UI,
Choose a member,
Try and change their rank.

#### Expected Behaviour
Their rank would change.

#### Actual Behaviour
Blocked UI Action dialogue appears.

#### Debug Output
1x [ADDON_ACTION_FORBIDDEN] AddOn 'MountsJournal' tried to call the protected function 'SetGuildRankOrder()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetGuildRankOrder'
[string "@Blizzard_Communities\GuildRoster.lua"]:174: in function `func'
[string "@FrameXML\UIDropDownMenu.lua"]:895: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

#### Screenshots
N/A

**Comment by sfmict** [comment]
Hi, I fixed this error in version 8.3.2-beta1.
Please check if this error is reproducing.

**Comment by CTOUT** [comment]
Hi @sfmict,

I can confirm the error does not occur in 8.3.2-beta2.

Thank you.
