### ISSUE TITLE
mount list is lost when addon reload

### ISSUE THREAD

**Issue by WeijieH** [sfmict/MountsJournal#20]
#### Environment
* Addon version: 10.2.17
* WoW version: 10.2

#### Steps to reproduce
Relogin, or just /rl, mount list is lost.

#### Expected Behaviour
mount list should be saved

#### Actual Behaviour
mount list is lost. Everything start from an empty list

#### Debug Output
No debug or error

#### Screenshots
--

**Comment by sfmict** [comment]
Hello. I can't reproduce this behavior, mb u rolled back to 10.2.14 version or older and installed a new one, then this is true, but I can't fix it, sorry.
If I'm wrong, please load your settings from `wow/_retail_/wtf/Account/accID/SavedVariables/MountsJournal.lua`

**Comment by sfmict** [comment]
Fixed, thx for the feedback and sorry for that situation :(

**Comment by nancikennedy** [comment]
> Fixed, thx for the feedback and sorry for that situation :(
Your welcome. I can confirm that the v.18 is saving things. :)
