### ISSUE TITLE
Feature Request: Add a filter for Mount "Family"

### ISSUE THREAD

**Issue by nancikennedy** [sfmict/MountsJournal#21]
#### Environment
* Addon version: Latest
* WoW version: Retail 10.2.7

#### Desired functionality

A "Family" filter

I use Mount Journal Enhanced alongside your addon, as MJE has a "Family" filter that is very useful at times. The downside is that MJE "hidden" and MJ "hidden" aren't the same, so I have to maintain two lists with hidden mounts to declutter my list. If MJ had a family filter that worked like MJE's did, I would be able to do all of my mount stuff with just your addon.

**Comment by sfmict** [comment]
HI, I'll add it when I have free time :)

**Comment by sfmict** [comment]
Added, check :)

**Comment by nancikennedy** [comment]
This makes me so happy! Thanks for doing this. :)
