### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by cheeseslicer** [sfmict/MountsJournal#22]
#### Environment
retail 11.0

#### Actual Behaviour

2x MountsJournal/Old.lua:145: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[C]"]: in function `(for generator)'
[string "@MountsJournal/Old.lua"]:145: in function <MountsJournal/Old.lua:143>
[string "@MountsJournal/Old.lua"]:156: in function `profileToSpell'
[string "@MountsJournal/Old.lua"]:178: in function <MountsJournal/Old.lua:20>
[string "@MountsJournal/Old.lua"]:294: in function `setOldChanges'
[string "@MountsJournal/Mounts.lua"]:142: in function `?'
[string "@MountsJournal/Mounts.lua"]:8: in function <MountsJournal/Mounts.lua:8>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by sfmict** [comment]
Hi, fixed, thx u for the feedback :)

**Comment by cheeseslicer** [comment]
Glad i could be of assistance. I tried looking into it myself, but without much knowledge of the new changed Blizz API wasn't sure what needed changed/fixed. Glad you could get it fixed. Love this addon mainly cause its a QOL addon for me

**Comment by sfmict** [comment]
Thx u for such kind words, it’s very nice to hear it :)
