### ISSUE TITLE
How to contribute to the localization?

### ISSUE THREAD

**Issue by Ulu2005** [sfmict/MountsJournal#23]
Hey I'd like to contribute for some translation, but CurseForge "Localization" page for zhTW doesn't seem to be active. It has some translated entries but they are left unreviewed since 2022. I wonder would submit a PR at Github would be the right way for this project?

**Comment by sfmict** [comment]
Hi, previewed doesn't necessarily mean it's not used, I'm just too lazy to click everything :)

**Comment by Ulu2005** [comment]
Gotcha, thanks!
