### ISSUE TITLE
Zone Condition Isn't Working for meta zones

### ISSUE THREAD

**Issue by ZaViper** [sfmict/MountsJournal#28]
Any Environment
* Addon version: 11.0.25
* WoW version: 11.0.2

When I was using the Zone condition with either "The Shadowlands" or "Shadowlands" the condition wasn't true when in the Shadowlands.

I tried to set up a rule condition to use Soulshape but only when I was in Shadowlands. It would however work if I put in Oribos or some other subzone. I was hoping that I could just put "Shadowlands" and it would cover all zones in Shadowlands.

Nothing happened.

**Comment by sfmict** [comment]
Hi, the Zone checks only current zone/subzone, without propagation :)

**Comment by ZaViper** [comment]
Alright, thank you!
