### ISSUE TITLE
Mount preview for the map tab

### ISSUE THREAD

**Issue by Prentius** [sfmict/MountsJournal#29]
Hi, we used to be able to preview the mount model when selecting mounts for a specific map. Now if we go in the map tab we cannot see the mounts anymore. It would be nice to have that option again or to be able to select the map from the model tab.

**Comment by sfmict** [comment]
Hi, I was thinking of adding the mount model to the tooltip when it isn't visible... So mb I'll make it :)

**Comment by sfmict** [comment]
Added :)
