### ISSUE TITLE
Profiles not saving favorite mounts correctly 

### ISSUE THREAD

**Issue by clmcgrath** [sfmict/MountsJournal#3]
#### Environment
* Addon version: 8.3.2 
* WoW version: 8.3 

#### Steps to reproduce
Create multiple profiles using the dropdown ,  i used copy current profile option 
Set different favourites on each profile 
switch between and you will notice the favorites save across all profiles , but the flying land and under water icons change with profile 

#### Expected Behaviour
The favourites should be saved per profile and change when switching profiles in the same fashion as the fly.land underwater icons do 

#### Actual Behaviour
the favorites  save to every profile instead of the currently selected profile

**Comment by sfmict** [comment]
Favorites mounts do not participate in the work of the addon. Only selected ones influence the summon.

**Comment by clmcgrath** [comment]
I see ,  is there a better way to sort these or find the ones selected

**Comment by clmcgrath** [comment]
nm i found it ,  thanks for the info
