### ISSUE TITLE
Can an "Instance" condition be added?

### ISSUE THREAD

**Issue by ZaViper** [sfmict/MountsJournal#31]
I’ve been experimenting with the Zone condition feature, and while it’s quite useful, I’ve found it to be somewhat limited in specific cases. For instance, I wanted to set up a rule for Soulshape that would trigger only when in the Shadowlands, where the ability is usable. However, in the current system, I would need to create separate rules for each Shadowlands zone, which can become a bit cumbersome.

I’ve seen similar functionality in addons like M6 and Opie, where there are macro conditionals that allow for broader zone-based triggers (e.g., Kalimdor, Northrend, Shadowlands, Dragon Isles, etc.). It would be fantastic if something like this could be added to MountsJournal—allowing users to set conditions by larger zones or continents, rather than by individual zones.

**Comment by sfmict** [comment]
Hi, for mounts you can set a list for any zone etc. in the map tab. I'll think about adding something like that to the conditions :).

**Comment by ZaViper** [comment]
Hello! Thank you! Yeah Soulshape is a spell and not a mount so I wouldn't be able use Soulshape with the map feature. I appreciate the consideration! :)

**Comment by sfmict** [comment]
Added :)

**Comment by ZaViper** [comment]
Thank you! You are a legend!
