### ISSUE TITLE
Dawnbreaker dungeon Flying keybind doesn't work

### ISSUE THREAD

**Issue by panseit** [sfmict/MountsJournal#32]
While doing the Dawnbreaker dungeon I noticed that the keybind to fly during the phases doesn't work. It doesn't summon any mount. Even if you have set a flag for that dungeon.

**Comment by sfmict** [comment]
Hi, are you in combat and using a combat macro?

**Comment by sfmict** [comment]
hmm, that's very weird, I override the fly key for this dungeon, mb I have wrong id, can you use this command `/dump GetInstanceInfo()` on this dungeon and tell me the result?

**Comment by sfmict** [comment]
Mb you have a "only ground" flag for some this map or the parent.

**Comment by sfmict** [comment]
So, id is correct. Can you give me the addon settings from  `World of Warcraft\_retail_\wtf\Account\acc_id\SavedVariables\MountsJournal.lua`?

**Comment by sfmict** [comment]
You can set a flying mount as the ground for this dungeon, or set a buff or instance rule in the settings.

**Comment by sfmict** [comment]
Hmm, mb it's because of the Halloween mount. I can't check right now, but you can set a rule for this instance on a specific mount.

**Comment by sfmict** [comment]
Is it in combat or not? In combat you have enabled the combat macro for all classes, so you need to set a rule for buff or debuff on a specific mount (not random mount).

**Comment by sfmict** [comment]
> If a rule is set will it override the summon in combat option?

Unfortunately no, blizz doesn't allow to change it in combat :(

**Comment by sfmict** [comment]
Np, gl :)
