### ISSUE TITLE
Suggestion: Prioritize Soar on Dracthyr characters setting toggle

### ISSUE THREAD

**Issue by penguinsane** [sfmict/MountsJournal#34]
#### Environment
* Addon version: 11.0.36
* WoW version: 11.0.5

**Comment by sfmict** [comment]
Hi, you can do it in the rules :)

**Comment by penguinsane** [comment]
Oops, you're right! I managed to figure it out. Thank you, sorry for the trouble. :)

(For anyone who comes in later to try and figure it out, I'll include a screenshot of the rule I made.)
![image](https://github.com/user-attachments/assets/5f5e0014-5df2-4ae4-bbcd-6c2312b3bccb)
