### ISSUE TITLE
Grizzly Hills Packmaster

### ISSUE THREAD

**Issue by Mnshamalan** [sfmict/MountsJournal#35]
#### Environment
* Addon version: v11.0.37
* WoW version: v11.0.5.57292

#### Desired functionality
Allow us to use the New Grizzly Hills Packmaster as the auto summoned mount if our durability is less than the set limit

**Comment by sfmict** [comment]
Wow, hi, I didn't know about that xD, will add it now

**Comment by sfmict** [comment]
Added, thx you for the feedback :)
