### ISSUE TITLE
Ground Mount button seems completely broken

### ISSUE THREAD

**Issue by Fred-IV** [sfmict/MountsJournal#36]
#### Environment
* Addon version: 11.0.42 
* WoW version: 11.0.5.57689 

#### Steps to reproduce
Just try to use the ground mount button (the horse), with several ground only mounts marked in your favorites. It won't work.
It will always summons the Chauffeur Motorcycle (https://www.wowhead.com/spell=179245)

#### Expected Behaviour
Summon random ground mounts that I have marked as a favorite. Not always the same mount.

#### Actual Behaviour
It always summons the Chauffeur Motorcycle (https://www.wowhead.com/spell=179245)

#### Debug Output
No bugs in debugger.

**Comment by sfmict** [comment]
![image](https://github.com/user-attachments/assets/c4e731c2-f389-4e1f-b42c-d552c0466f9e)
