### ISSUE TITLE
Can you expand the action "Use macro before mounting"

### ISSUE THREAD

**Issue by ZaViper** [sfmict/MountsJournal#38]
#### Environment
* Addon version: v11.0.43
* WoW version: 11.0.5

#### Desired functionality
When using "Use macro before mounting" the rules skip it if I'm in an area where I can't mount, but would like the macro to trigger anyways.

For an example, I have OPie set up in such away that makes it easy to put on any gear that allows me to teleport to somewhere else. After teleporting I then use MountsJournal rules to fix my gear, putting back on my main equipment after teleporting, because usually the first thing I do is mount up after teleporting somewhere. But when I teleport to a place I can't mount like the Stormwind portal room I'd like the macro to trigger when I use the MountsJournal rules when using it to trigger a speed ability to move through the room quickly.

**Comment by sfmict** [comment]
Hi, you can use macro action in that zone or indoors etc.
