### ISSUE TITLE
Two requests for Mounts Journal

### ISSUE THREAD

**Issue by tyrexis26** [sfmict/MountsJournal#4]
Mounts Journal is by far the most superior mount addon I've used, and I love it.  I just have two requests.

1) Target mount copy
If you target someone and click on the macro, it will try to copy the mount they are riding.
2) Add the second herbalism mount, Mechanized Lumber Extractor, and randomly call one of the two if both are owned and the Herbalism flag is checked.

Thank you!

**Comment by sfmict** [comment]
Hello, it's easy :).

**Comment by tyrexis26** [comment]
Thank you!!
