### ISSUE TITLE
Summon mount uses incorrect mount list in De Other Side Instance 

### ISSUE THREAD

**Issue by clmcgrath** [sfmict/MountsJournal#7]
#### Environment
* Addon version: 9.0.9
* WoW version: 9.0.2

#### Steps to reproduce
Enter De Other Side Instance 
Summon mount 

#### Expected Behaviour
Should summon ground mount as flying is not available 

#### Actual Behaviour
Summons flying mount 

This appears to be working correctly in other outdoor instances (ie plaguefall, Opening area of Theater of Pain, Necrotic Wake) ,  I have only noticed this happening in De Other Side 
Perhaps this instance is not classified properly in region detection ?

**Comment by sfmict** [comment]
Hi, thx for feedback, check out [the latest beta version](https://github.com/sfmict/MountsJournal/releases/tag/v9.0.10-beta2) :).
