### ISSUE TITLE
Selection for mounts gone

### ISSUE THREAD

**Issue by grafter671** [sfmict/MountsJournal#8]
#### Environment
* Addon version: v9.1.2
* WoW version: 9.1.0
The buttons to make a mount be summoned by the addon are gone. (see marked square in screencap) 

![image](https://user-images.githubusercontent.com/87325294/125318965-a1608e00-e33a-11eb-8242-bec9ca7b42e4.png)

**Comment by sfmict** [comment]
You have Mount Journal Enhanced addon installed. MountsJournal doesn't work with him yet.
